import sgMail from "@sendgrid/mail";

sgMail.setApiKey(process.env.SENDGRID_API_KEY!);

const FROM = {
  email: process.env.SENDGRID_FROM_EMAIL!,
  name: process.env.SENDGRID_FROM_NAME ?? "Stakeholder Register",
};

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "";

export async function sendMonthlyReminder(to: string, name: string): Promise<void> {
  const msg = {
    to,
    from: FROM,
    subject: "[Action Required] Stakeholder Register — Monthly Update Due",
    html: `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Monthly Update Reminder</title>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #f4f6f9; margin: 0; padding: 0; }
    .container { max-width: 600px; margin: 40px auto; background: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
    .header { background: #4f46e5; padding: 32px 40px; }
    .header h1 { color: #ffffff; margin: 0; font-size: 22px; font-weight: 600; }
    .body { padding: 32px 40px; color: #374151; }
    .body p { line-height: 1.6; margin: 0 0 16px; }
    .cta { display: inline-block; margin-top: 24px; padding: 14px 28px; background: #4f46e5; color: #ffffff; text-decoration: none; border-radius: 6px; font-weight: 600; font-size: 15px; }
    .footer { padding: 20px 40px; background: #f9fafb; color: #9ca3af; font-size: 12px; border-top: 1px solid #e5e7eb; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Stakeholder Register — Monthly Reminder</h1>
    </div>
    <div class="body">
      <p>Dear ${name},</p>
      <p>This is your <strong>monthly reminder</strong> to review and update the Stakeholder Register for your projects.</p>
      <p>Please ensure the following are current and accurate:</p>
      <ul>
        <li>Stakeholder contact information (email, phone)</li>
        <li>Influence and power levels</li>
        <li>Teams availability status</li>
        <li>FTE counts (Signed vs Deployed)</li>
        <li>Active processes in each project</li>
      </ul>
      <a href="${APP_URL}/dashboard" class="cta">Update Stakeholder Register &rarr;</a>
    </div>
    <div class="footer">
      This email was automatically generated by the Stakeholder Register system on the last Friday of the month.<br/>
      If you believe you received this in error, please contact your system administrator.
    </div>
  </div>
</body>
</html>
    `.trim(),
  };

  await sgMail.send(msg);
}

export async function sendInviteEmail(to: string, name: string, tempPassword: string): Promise<void> {
  const msg = {
    to,
    from: FROM,
    subject: "You have been invited to the Stakeholder Register",
    html: `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #f4f6f9; margin: 0; padding: 0; }
    .container { max-width: 600px; margin: 40px auto; background: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
    .header { background: #4f46e5; padding: 32px 40px; }
    .header h1 { color: #ffffff; margin: 0; font-size: 22px; font-weight: 600; }
    .body { padding: 32px 40px; color: #374151; }
    .body p { line-height: 1.6; margin: 0 0 16px; }
    .credentials { background: #f3f4f6; border-radius: 6px; padding: 16px 20px; margin: 20px 0; font-family: monospace; font-size: 14px; }
    .cta { display: inline-block; margin-top: 24px; padding: 14px 28px; background: #4f46e5; color: #ffffff; text-decoration: none; border-radius: 6px; font-weight: 600; font-size: 15px; }
    .footer { padding: 20px 40px; background: #f9fafb; color: #9ca3af; font-size: 12px; border-top: 1px solid #e5e7eb; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Welcome to Stakeholder Register</h1>
    </div>
    <div class="body">
      <p>Dear ${name},</p>
      <p>You have been invited to the <strong>Stakeholder Register</strong> system. Your account has been created with the credentials below.</p>
      <div class="credentials">
        <strong>Email:</strong> ${to}<br/>
        <strong>Temporary Password:</strong> ${tempPassword}
      </div>
      <p><strong>Please change your password immediately after logging in.</strong></p>
      <a href="${APP_URL}/login" class="cta">Log In Now &rarr;</a>
    </div>
    <div class="footer">
      If you did not expect this invitation, please ignore this email or contact your system administrator.
    </div>
  </div>
</body>
</html>
    `.trim(),
  };

  await sgMail.send(msg);
}
